---
apiVersion: v2
description: Quickwit
name: quickwit
version: 0.1.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
