---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  ports:
    - name: "http"
      port: {{ $.Values.http_port }}
      targetPort: 7280
    - name: "grpc"
      port: {{ $.Values.otlp_grpc_port }}
      targetPort: 7281
  selector:
    app: {{ include "common.names.fullname" . }}
