---
replicas: 1
service_port: 8089
restartPolicy: Always
wait_time: 10
image:
  path: comworkio/imalive-api
  tag: latest

log:
  level: INFO
  format: json
  otlp_endpoint: 0.0.0.0:4317

ingress:
  enable: false
